### ISSUE TITLE
IP address 0.0.0.0:0

### ISSUE THREAD

**Issue by krupaw2** [horihiro/esp8266-google-home-notifier#12]
Any suggestion?

connecting to Google Home...
found Google Home(0.0.0.0:0)
Google Home's IP address/port is not set. Call 'device' or 'ip' method before calling 'cast' method.

**Comment by horihiro** [comment]
I haven't experienced that.

Could you please check your Google Home'a IP address using Google Home App for smartphone?

**Comment by krupaw2** [comment]
My address is 192.168.0.100

I try add:
ghn.ip(192.168.0.100, "en", 5353);
but i recive compilation error:
GoogleSay:30:8: error: too many decimal points in number

 ghn.ip(192.168.0.100, "en", 5353);

**Comment by horihiro** [comment]
The type of first argument of method `ip()` is `IPAddress` class.

Please refer to following.
https://www.arduino.cc/en/Reference/EthernetIPAddress

And Google Home uses port 8009 usually.
How did you decide the port number?

**Comment by krupaw2** [comment]
Thank you very much for your commitment.
I found such a hint somewhere on YT

I changed to:
ghn.ip ((192, 168, 0, 100), "en", 8009);
Now it compiles correctly, but unfortunately it does not work - receives message:
found Google Home (100.0.0.0:8009)

Ok, now its working:

  IPAddress ip(192, 168, 0, 100);
  ghn.ip(ip, "en", 8009);

**Comment by horihiro** [comment]
could I close this issue?

**Comment by krupaw2** [comment]
Of course - everything works perfectly :)
