### ISSUE TITLE
language

### ISSUE THREAD

**Issue by jeanbatfr** [horihiro/esp8266-google-home-notifier#21]
Hello, 
i don't find how to change the language of the phrase?
Thank you

**Comment by horihiro** [comment]
Which language do you want to use?
\# I tested only `en` (English) and `ja` (Japanese).

Can you use the second argument of `device` method?
https://github.com/horihiro/esp8266-google-home-notifier/blob/master/examples/esp8266/SimpleUsage/SimpleUsage.ino#L29

**Comment by jeanbatfr** [comment]
Hello,
ok, I was not sure about the purpose of this argument, so if I use "fr" it will be french?

**Comment by horihiro** [comment]
maybe yes
I haven't tried `fr` because I cannot understand French.

Please try it.

**Comment by jeanbatfr** [comment]
Yes, it's working!
Amazing project, well done ;)

PS : Maybe you should add a comment to explain the arguments of device, for next users :)
