### ISSUE TITLE
Failed to get TKK. trying again... 

### ISSUE THREAD

**Issue by trevorf999** [horihiro/esp8266-google-home-notifier#26]
Hi,
    When trying to send Notification to Google assist I get 

connecting to Wi-Fi...
connected.
IP address: 192.168.XXX.XXX
connecting to Google Home...
found Google Home(192.168.XXX.XXX:8009)
Failed to get TKK. trying again...  (current: 0, maxRetry: 10)
Failed to get TKK. trying again...  (current: 1, maxRetry: 10)

 I have confirmed that I can get to Google Translate Service on the network. and the esp is able to get to the web.  Any suggestions

**Comment by horihiro** [comment]
Dup of https://github.com/horihiro/esp8266-google-tts/issues/12
