### ISSUE TITLE
Failed to get TKK

### ISSUE THREAD

**Issue by MauriceMcGuigan** [horihiro/esp8266-google-home-notifier#28]
Had an ESP8266 project running for some while using the Google Home Notifier and Google TTS, but now stops after connecting with error:

Failed to get TKK - trying again.......
This repeats 10 times and then resets the cycle

Tried a new basic code installation using single word output, but does the same.
Have the latest .h files installed.
Any clues welcome

**Comment by horihiro** [comment]
This is `esp8266-google-tts` 's issue.

Dup of https://github.com/horihiro/esp8266-google-home-notifier/issues/26
